### PR TITLE
Focus Assignment

### PR DESCRIPTION
**Pull request by jiheekim93**

### CODE REVIEW

**Comment by code-warrior** [comment]
Please delete the `.DS_Store` file from the `css` folder, then sync your repo. It will update here.

**Comment by jiheekim93** [comment]
[image: Inline image 1]

I don't see that file in the css folder

**Comment by jiheekim93** [comment]
I only added style.css, and the html file, but there was 3 changes and i
tried to find where that file is coming from.

That is why i asked you the question because i was confused.

I knew how to pull the request with the right files but still have no clue
how to find the file

**Comment by jiheekim93** [comment]
wait! i think i could delete it from Atom. Can you check it is deleted?

**Comment by code-warrior** [comment]
It’s fine now. Please do not make any more changes.

**Pull request merged**
